### ISSUE TITLE
[SUGGESTION] Plant weed outside

### ISSUE THREAD

**Issue by MichaelSasser** [qbcore-framework/qb-weed#45]
**Is your feature request related to a problem? Please describe.**
Being able to plant weed in houses is quite interesting, but having the possibility to plant it outside too, with configurable growth times, would be a nice addition. The police fraction can use their resources to find the plants and observe their owners. This would give the players entirely new RP situations.

**Describe the feature you'd like**
Extend `qb-weed` to allow server owners to enable a feature which makes it possible to grow plants outside houses in configurable areas (PolyZones). 

**Describe alternatives you've considered**
There are other resources, that do exactly that, but a well integrated native solution would be preferable.

**Comment by jeann2013** [comment]
@MichaelSasser You can make  plant target with qb-target, please see https://github.com/qbcore-framework/qb-target/blob/main/TEMPLATES.md

**Comment by OfficialRDB** [comment]
Or just remove the check if they are in a house.

**Comment by Soldierofthelam** [comment]
this script has never worked proper for me since release the weed plants bug out if you plant in the house, If you leave and come back in the house the plants are always showing high off the ground or you can never access them once they've fully grown I've found this to be one of qbcore weakest scripts. It would be nice to se some sort of weed growing script that isn't bound to the house plants in the scripts , and grown them anywhere outside.

**Comment by h1ker6s** [comment]
> Or just remove the check if they are in a house.

how?
